lukevella/rallly

.github/workflows/cd.yml
This adds a simple workflow to build Docker images via Github Actions and push them to Github's container registry.
This will only happen for tagged commits or when run manually from *Actions*. To add a tag:
```
$ git tag -a v0.2
$ git push origin v0.2
```
This could be adjusted to e.g. use SHAs as tags or run more often.
This should automatically use the repo's permissions after merging, so no further setup needed.
Test package here: https://github.com/m3nu/rallly/pkgs/container/rallly
=> Add Docker publishing workflow

README.md, sample.env
I had the following error in my docker logs:
```bash
rallly-rallly-1 | Error: iron-session: Bad usage. Password must be at least 32 characters long.
rallly-rallly-1 | at file:///usr/src/app/node_modules/iron-session/dist/index.mjs:24:13
rallly-rallly-1 | at Array.forEach (<anonymous>)
rallly-rallly-1 | at getIronSession (file:///usr/src/app/node_modules/iron-session/dist/index.mjs:22:76)
```
=> fixed min length of SECRET_PASSWORD.

docker-compose.yml
This patch passes the explicit path to the prisma schema so that the initial table creation is performed.  Otherwise the command will print:
No migration found in prisma/migrations
And attempting to create a poll produces the postgres error:
ERROR:  relation "public.users" does not exist at character 35
STATEMENT:  SELECT "public"."users"."id" FROM "public"."users" WHERE "public"."users"."email" = $1 OFFSET $2
=> docker-compose: pass schema to migrate deploy

Dockerfile
This reduces the final image from ~2.1gb to ~900mb. I honestly don't really understand node and yarn enough to know what was consuming all that extra space (I assume some sort of build dependency), but the final size of `/usr/src/app` was/is 820mb so the new image size of 900mb checks out.
=> Shrink docker image with multi-stage build

Dockerfile, docker-compose.yml
This is required for a successful startup, so this makes it the
default command rather than requiring it to be overridden in the
compose file.
=> Move prisma command to Dockerfile

Dockerfile, docker-compose.yml, docker_start.sh
Closes #170
This PR removes the `DATABASE_URL` from the Dockerfile and moves the CMD in the last line to a startup script.
Additionally, the docker compose performs a health check on the database container to wait until is fully functional to avoid refused connections that could sometims occur on the first run when the database was created.
I'm no Prisma expert but this seems to work without the need to override the `datasources` field in the `PrismaClient`. Prisma only complains when the env variable is not set upon startup.
=> Remove DATABASE_URL from Dockerfile

.github/workflows/docker-image.yml, docker-compose.yml
Now that #170 is fixed, we can add a CI/CD workflow to automatically push a Docker image to Dockerhub. Only thing you need to do is to add secrets for your Dockerhub credentials.
=> CI/CD: Automatically publish Docker image

.github/workflows/docker-image.yml
Since updating the workflow to support arm architectures this workflow now takes around an hour to finish. I'm assuming that it is a bit overkill to publish an image for every commit here. So instead moving to a weekly build whereby an image is published every Monday at 06:00 am UTC instead.
=> Run docker workflow once a week

src/server/routers/login.ts
The contact link is rendered as "mailto:undefined" in the magic link emails
=> Set supportEmail when rendering login template

package.json, yarn.lock
Seeing lots of hydration errors in production. Might be related to this: https://github.com/vercel/next.js/issues/44083
Downgrading to `next@13.0.6` to try and reduce the transactions being made to sentry.
=> Downgrade nextjs

package.json, yarn.lock
Fixes a warning about some dependencies not support typescript 4.9.0
=> Update eslint parser

src/components/date-card.tsx, src/components/home/poll-demo.tsx, src/components/poll/desktop-poll/poll-header.tsx
Previously we stopped showing the day of week for date options. This was a bad idea since users clearly found this very useful.
=> 💄 Bring back showing the day of the week for date options

src/components/forms/poll-options-form/month-calendar/month-calendar.tsx
Set start time of new time slot to end of previous slot
Currently, the time slots all start at the same time. This is cumbersome and creates additional effort when creating polls.
This pull request sets the start time of the new time slot to the end time of the previous time slot. This allows users to create successive time slots with just a few clicks.
see https://github.com/lukevella/rallly/discussions/138
=> Improve time slot start times

apps/web/declarations/environment.d.ts, apps/web/next.config.js, apps/web/public/locales/en/app.json, apps/web/src/components/auth/login-form.tsx, apps/web/src/components/layouts/standard-layout/user-dropdown.tsx, apps/web/src/pages/admin/[urlId].tsx, apps/web/src/pages/demo.tsx, apps/web/src/pages/home.tsx, apps/web/src/pages/login.tsx, apps/web/src/pages/new.tsx, apps/web/src/pages/profile.tsx, apps/web/src/server/routers/auth.ts, apps/web/src/server/routers/polls.ts, apps/web/src/server/routers/polls/demo.ts, apps/web/src/server/trpc.ts, apps/web/src/utils/auth.ts, turbo.json
Many self-hosters ask to be able to secure their instance to prevent unauthorized users from creating polls on their instance. This update addresses this issue by adding the following configuration properties:
|Name| Default | Description
|---| ---| --- |
| `AUTH_REQUIRED` | `false` | Set to `true` to require authentication for creating new polls and accessing admin pages |
| `ALLOWED_EMAILS` | `""` |  Comma separated list of email addresses that are allowed to register and login.<br>If not set, all emails are allowed.<br><br>Wildcard characters are supported.<br><br>Example: `"user@email.com, *@example.com, *@*.example.com"` |
| `DISABLED_LANDING_PAGE` | `false` | Set to `true` to take users straight to the app   |
=> 🔓 Add config to secure instance from unauth users

apps/web/src/components/discussion/discussion.tsx
Currently, each comment has a menu, with a button to delete the comment. If the user is not allowed to delete the comment, the button is disabled (see first screenshot).
With this pull request the menu button is only shown if necessary. This reduces clutter and improves the user experience.
Before:
After:
=> 💄 Hide comment dropdown menu when unavailable to user

apps/web/package.json, apps/web/src/components/admin-control.tsx, apps/web/src/components/auth/login-form.tsx, apps/web/src/components/create-poll.tsx, apps/web/src/components/discussion/discussion.tsx, apps/web/src/components/participant-dropdown.tsx, apps/web/src/components/poll/manage-poll/delete-poll-form.tsx, apps/web/src/components/poll/mutations.ts, apps/web/src/components/user-provider.tsx, apps/web/src/pages/_app.tsx, apps/web/src/pages/demo.tsx, apps/web/src/utils/posthog.ts
Discussed in #584, the way we currently initialize posthog results in a failed request for self-hosters and environments where posthog is not configure. This cleans that up by conditionally calling `posthog.init()` inside `_app` and using `PostHogProvider` to supply the `posthog` instance through React context.
=> 📈 Conditionally initialize posthog

apps/web/src/components/layouts/standard-layout/mobile-navigation.tsx
Currently when you scroll and the header gets sticky, there is a weird transition going on:
https://user-images.githubusercontent.com/1368405/227801805-c5f5f506-6949-44fe-be8c-f05db04dfc51.mp4
This PR removes the `transition-all` class to make the switching between sticky and non sticky smoother:
https://user-images.githubusercontent.com/1368405/227801873-e5992d31-e2be-4d5f-be73-b9163f97526c.mp4
=> Remove transition-all to remove weird transition

packages/backend/trpc/routers/auth.ts
The matcher was not escaping special characters which may have caused it to work in unexpected ways. This change escapes all special regex characters except for "*" which is converted to ".*" to act as a wildcard character.
This might fix #859
=> 🐛 Fix allowed email address matcher

apps/web/src/components/user-provider.tsx
Temporary fix to avoid the app from rendering twice for subscribed users. To be removed once #874 is ready
=> 🐛 Fix double render for subscribed users

apps/web/src/utils/auth.ts, apps/web/src/utils/auth/custom-prisma-adapter.ts, apps/web/src/utils/auth/verification-token-fix.ts
This changed address an issue that is being discussed here: https://github.com/nextauthjs/next-auth/discussions/4585
The issue:
Verification tokens can only be used once by default. This means that once a magic link is used the verification token is deleted. This causes issues for some users that have inboxes that checks links inside emails because the link ends up being consumed by the inbox which means the verification token is deleted by the time the user sees the email.
The solution:
We customize the prisma adapter such that the verification token is not deleted when it is used. To avoid accumulating verification tokens, we delete any existing verification tokens for the same identifier before creating new ones.
This is a temporary solution until a better one is found.
=> 🐛 Fix magic link consumed before user gets it

apps/web/tests/authentication.spec.ts, packages/database/prisma/migrations/20231027074632_nextauth_ci_identifiers/migration.sql, packages/database/prisma/schema.prisma
The email identifier used in verification tokens would not match when using the 6-digit code login if the user types it in different to how it is stored in the database. To fix this, we modify the schema to make the identifier case insensitive.
=> 🐛 Make identifier in verification tokens case insensitive

apps/web/src/components/auth/auth-forms.tsx
Fix #924.
Self-hosted instances cannot use `NEXT_PUBLIC_BASE_URL` on client side code because this value is set during build time which defaults to `localhost:3000`.
=> 🐛 Use current origin as base url for code verification

apps/web/src/contexts/preferences.tsx
Avoid preferences from silently failing if preferences context doesn't exist
=> 🔨 Ensure preferences context is present

apps/web/src/app/[locale]/(auth)/login/page.tsx
Make sure the login page is dynamically rendered to use runtime values for OIDC config. Fix for #697.
=> 🐛 Dynamically render login page

apps/docs/contribute/documentation.mdx, apps/docs/contribute/translations.mdx, apps/docs/guide/participant-guide.mdx, apps/docs/introduction.mdx, apps/docs/self-hosting/introduction.mdx, apps/docs/workflow/create.mdx, apps/docs/workflow/finalize.mdx, apps/docs/workflow/invite.mdx
Sometimes images inside a ``Frame`` component showed a scrollbar, allowing users to scroll the image out of the bounds of the frame.  
By using the HTML ``img`` element inside a ``Frame`` component (as shown in the [docs](https://mintlify.com/docs/content/components/frame)) instead of Markdown images the issue gets fixed with no noticeable changes.
=> Fix docs images being scrollable

apps/web/src/pages/api/auth/[...nextauth].ts, apps/web/src/utils/auth.ts
Follows the advice in the next-auth docs for handling HEAD requests in the `[...nextauth]` route.
See: https://next-auth.js.org/tutorials/avoid-corporate-link-checking-email-provider
=> 🐛 Fix issue where verification links would automatically get consumed by link checkers

apps/web/sentry.client.config.ts
We suspect this might be causing hydration errors. Disabling to see if it fixes it.
=> 🔧 Disable session replay
