lukevella/rallly

views/index.jade

Also my editor removed trailing whitespace automatically :)

GitHub has a capital H

---

api-client/create-demo.ts
components/forms/poll-options-form/month-calendar/month-calendar.tsx
components/forms/poll-options-form/month-calendar/time-picker.tsx
components/modal/modal.tsx
components/switch.tsx
pages/api/poll/demo.ts
tests/edit-options.spec.ts

* Added test thats a poll and ensures that a warning is shown when deleting options
* Stop event propagation on modal to avoid closing the modal unintentionally.

Make demo values fixed

---

Dockerfile
docker-compose.yml

Fix missing base url during docker build

---

src/components/poll/manage-poll.tsx

Prevent modal from closing when clicking outside

---

src/components/create-poll.tsx
src/components/forms/poll-options-form/date-navigation-toolbar.tsx
src/components/page-layout/footer.tsx
src/components/poll/language-selector.tsx
src/components/preferences.tsx

Fix issue where locale appears in URL unexpected when changing language in the app.

Fix locale routing

---

src/pages/poll.tsx

Fixes issue where full page loader appears within the standard layout.

Move participants provider

---

src/utils/dayjs.tsx

Avoid showing the default locale before the desired locale is ready.

Wait for dayjs locale to load before rendering

---

templates/login.html
templates/new-comment.html
templates/new-participant.html
templates/new-poll-verified.html
templates/new-poll.html

Make email logo use template var

---

Dockerfile
docker-compose.yml

Remove base url arg

---

src/utils/send-email.ts

Log error when email fails to send

---

public/locales/en/app.json
src/components/standard-layout.tsx

Missing i18n

---

prisma/migrations/20221026220835_add_indexes/migration.sql
prisma/schema.prisma

Trying to speed up requests for this rows

Add index to participant and votes table

---

src/components/forms/poll-options-form/month-calendar/month-calendar.tsx
src/components/forms/poll-options-form/month-calendar/time-picker.tsx

Patching this bug. This component will be replaced in the next major release. Closes #221

Fix bug when end time calculation is after midnight

---

src/pages/_app.tsx

Adjust viewport

---

style.css

Fix scrolling behavior in safari

---

.github/workflows/docker-image.yml

Update workflow to build an image for arm platforms #175

Update docker image workflow for arm support

---

src/pages/home.tsx

Server render homepage

---

src/server/routers/login.ts
src/utils/api-utils.ts
templates/login.ts

Update template loading

---

package.json
src/pages/_app.tsx
src/pages/_document.tsx
style.css
tailwind.config.js
yarn.lock

Use next/font to serve fonts

---

Dockerfile
docker-start.sh

Exit script on error

---

next.config.js
src/components/create-poll.tsx
src/components/discussion/discussion.tsx
src/components/home.tsx
src/components/layouts/page-layout.tsx
src/components/layouts/page-layout/footer.tsx
src/components/layouts/standard-layout.tsx
src/components/poll.tsx
src/components/poll/desktop-poll/participant-row.tsx
src/components/poll/mobile-poll.tsx
src/components/poll/mutations.ts
src/components/poll/poll-subheader.tsx
src/pages/admin/[urlId].tsx
src/pages/p/[urlId].tsx
src/pages/privacy-policy.tsx
src/pages/profile.tsx
src/server/routers/_app.ts
src/server/routers/polls.ts
src/utils/auth.ts
src/utils/trpc/types.ts

Working on uncoupling these pages.

Refactor admin and participant page

---

src/utils/dayjs.tsx

It appears this might be causing some issues in certain browser so removing it since it wasn't offering much value anyway.

Remove render block

---

src/server/routers/polls.ts
src/server/routers/polls/verification.ts
src/utils/api-utils.ts
templates/new-poll-verified.ts
templates/new-poll.ts
tests/create-delete-poll.spec.ts

Trying to make these lines more useful.

Improve usability of email subject lines

---

src/components/home/poll-demo.tsx
src/components/poll/mobile-poll/poll-option.tsx
src/components/poll/mobile-poll/time-slot-option.tsx
src/components/poll/score-summary.tsx

This update allows participants to see the score of an option while they are voting and allows them to see the full results when they are viewing the poll.
Close #485

✨ Improve usability of mobile poll

---

apps/web/src/server/routers/polls.ts
apps/web/src/server/routers/polls/participants.ts
apps/web/src/utils/api-utils.ts
apps/web/tests/create-delete-poll.spec.ts
apps/web/tests/vote-and-comment.spec.ts

Send multiple emails in parallel rather than sequentially.

⚡️ Make submitting a participant a bit faster

---

apps/web/src/utils/dayjs.tsx

see https://github.com/lukevella/rallly/issues/530
Fixes the following bug:  When you try to specify a time slot at the end of the day in week view, the application crashes.
https://user-images.githubusercontent.com/64426524/221411502-3d7a448c-ad03-45eb-be0f-9f79708ec37b.mp4

fix isSameOrAfter not a function bug

---

apps/web/Dockerfile
package.json

Just to make sure we’re not building anything we don’t need on vercel

👷‍♂️ Update build command

---

apps/web/src/components/home/poll-demo.tsx
apps/web/src/components/poll-context.tsx
apps/web/src/components/poll/desktop-poll/poll-header.tsx
apps/web/src/components/poll/mobile-poll/poll-option.tsx
apps/web/src/components/poll/score-summary.tsx
apps/web/src/server/routers/polls/demo.ts

✨ Highlight option with highest score

---

apps/web/public/locales/en/app.json
apps/web/src/components/profile.tsx
apps/web/src/server/routers/user.ts

Shows whether a poll is closed in the list

✨ Show poll status in list

---

apps/web/src/components/poll/truncated-linkify.tsx

Fixes an issue where links are not styled correctly

🎨 Fix links not styled correctly

---

README.md
package.json
packages/database/package.json
packages/database/prisma/seed.ts
yarn.lock

Fills the database with random data for development

👷‍♂️ Add db seed script

---

apps/web/src/components/user-provider.tsx
apps/web/src/pages/_app.tsx

The posthog cookie is not necessary since we already have our own cookie to identify a user's session.

🍪 Stop using posthog cookie

---

apps/landing/src/posts/mobile-ui-update.md
apps/landing/src/posts/rallly-3-0.md

**Fixing two typos within blog post**

V3.0.0 alpha

---

apps/web/src/components/forms/poll-options-form/month-calendar/month-calendar.tsx
apps/web/src/components/forms/poll-options-form/types.ts
apps/web/src/components/forms/poll-options-form/week-calendar.tsx
apps/web/src/pages/poll/[urlId]/edit-options.tsx
apps/web/src/utils/date-time-utils.ts

🐛 Fix issue with applying times after midnight

---

apps/landing/package.json
apps/web/package.json

Allows running package.json scripts from all platforms.

Add cross-env to scripts

---

sample.env

Fixes the error I faced in #761.
Should I also update https://support.rallly.co/self-hosting/configuration-options? I am not sure what to write there.

Add NEXT_PUBLIC_APP_BASE_URL to sample.env

---

apps/web/src/components/event-card.tsx
apps/web/src/pages/polls.tsx
apps/web/src/utils/dayjs.tsx

Fixes and issue where date is not adjusted correctly for time zone difference.
Also fixes an issue where the wrong time format might be shown for finalized polls.

🐛 Fix date and time formatting and tz adjustment

---

apps/web/public/locales/en/app.json
apps/web/src/components/poll/desktop-poll.tsx
packages/ui/button.tsx
packages/ui/tooltip.tsx

✨ Expand results

---

apps/web/package.json
packages/backend/package.json
yarn.lock

This should fix an issue where "CET" timezone would be interpreted as invalid.

📦 Bump spacetime

---

apps/web/package.json
apps/web/src/pages/_app.tsx
yarn.lock

We only use this on the landing page.

🧹 Remove vercel analytics

---

apps/landing/src/posts/rallly-3-0-self-hosting.md

📝 Update rallly-3-0-self-hosting.md

---

apps/web/src/pages/invite/[urlId].tsx

Fix unhandled error when invite page should be sending back a 404 error.

🐛 Fix 404 error on invite page

---

apps/web/src/utils/auth.ts
apps/web/src/utils/auth/merge-user.ts
packages/backend/trpc/routers/auth.ts

When logging in any polls, participants or comments created as a guest should be applied to your account.

🐛 Fix merge guest user into logged in user

---

apps/web/src/components/auth/auth-forms.tsx
apps/web/src/pages/auth/login.tsx

Send data to posthog to track login events

📈 Track login events in posthog

---

packages/database/prisma/seed.ts

Updated the seed script to create 3 users with different billing properties

🍃 Update seed script

---

apps/docs/self-hosting/managed-hosting.mdx

Added Elestio as managed hosting option
closes #913 

feat: Adding elestio as managed-hosting option

---

package.json
yarn.lock

Hoping this fix flaky CI tests

⬆️ Upgrade turbo
